<a href="https://colab.research.google.com/github/sriharsha8253/harsha/blob/main/week_4%2C5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
9
import numpy as np
def add_matrix_vector(x,y):
 assert len(x.shape)==2
 assert len(y.shape)==1
 assert x.shape[1] == y.shape[0]
 for i in range(x.shape[0]):
   for j in range(x.shape[1]):
     x[i,j]+=y[j]
 return x
x=np.array([[1,2],[3,4]])
y=np.array([10,20])
z=add_matrix_vector(x,y)
print(z)


[[11 22]
 [13 24]]


In [ ]:
10
#Tensor Reshaping.
import numpy as np
x = np.array([[1,2,3,4],[5,6,7,8]])
print("Before Reshaping")
print(x)
print("Shape of x tensor is",x.shape)
x = x.reshape(4,2)
print("\n After Reshaping x to 4 rows 2 columns")
print(x)
print("Shape of x tensor is",x.shape)
x = x.reshape(8,1)
print("\n After Reshaping x to 8 rows and 1 column" )
print(x)
print("Shape of x tensor is",x.shape)


Before Reshaping
[[1 2 3 4]
 [5 6 7 8]]
Shape of x tensor is (2, 4)

 After Reshaping x to 4 rows 2 columns
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape of x tensor is (4, 2)

 After Reshaping x to 8 rows and 1 column
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Shape of x tensor is (8, 1)


In [ ]:
11
def naive_vector_dot(x,y):
 assert len(x.shape)==1
 assert len(y.shape)==1
 assert x.shape[0]==y.shape[0]
 z=0.
 for i in range(x.shape[0]):
  z+=x[i]*y[i]
 return z
x= np.array([1,2,3,4])
y= np.array([10,20,30,40])
result= naive_vector_dot( x , y)
print(result)

300.0


In [ ]:
12
def naive_matrix_vector_dot(x, y) :
 assert len(x.shape) == 2
 assert len(y.shape) == 1
 assert x.shape[1] == y.shape[0]
 z = np.zeros(x.shape[0])
 for i in range(x.shape[0]) :
   for j in range(x.shape[1]) :
     z[i] += x[i, j] * y[j]
 return z
x= np.array([[1,2],[3,4]])
y= np.array([10,20])
result= naive_matrix_vector_dot(x,y)
print(result)


[ 50. 110.]


In [ ]:
13
import numpy as np
def naive_matrix_dot(x,y):
 assert len(x.shape)==2
 assert len(y.shape)==2
 assert x.shape[1]==y.shape[0]
 z=np.zeros((x.shape[0],y.shape[1]))
 for i in range(x.shape[0]):
   for j in range(y.shape[1]):
     row_x=x[i,:]
     col_y=y[:,j]
     z[i,j]=naive_vector_dot(row_x,col_y)
 return z
def naive_vector_dot(x,y):
 assert len(x.shape)==1
 assert len(y.shape)==1
 assert x.shape[0]==y.shape[0]
 z=0.
 for i in range(x.shape[0]):
    z+=x[i]*y[i]
 return z
x= np.array([[1,2],[3,4]])
y= np.array([[10,20],[30,40]])
result= naive_matrix_dot(x,y)
print(result)

[[ 70. 100.]
 [150. 220.]]


In [ ]:
14
#Tensors Reshaping.
import numpy as np
#Reshaping 1D Tensor
x = np.array([1,2,3,4])
print("Before Reshaping 1D Tensor")
print(x)
print("Shape of 1D tensor is",x.shape)
x = x.reshape(4,1)
print("After Reshaping 1D tensor to 4 rows 1 column")
print(x)
#Reshaping 2D Tensor
x = np.array([[1,2],[3,4]])
print("\n Before Reshaping 2D Tensor")
print(x)
print("Shape of 2D tensor is",x.shape)
x = x.reshape(4,1)
print("After Reshaping 2D tensor to 4 rows 1 column")
print(x)
#Reshaping 3DTensor
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\nBefore Reshaping 3D Tensor")
print(x)
print("Shape of 3D tensor is",x.shape)
x = x.reshape(8,1)
print("After Reshaping 3D tensor to 8rows 1 column")
print(x)


Before Reshaping 1D Tensor
[1 2 3 4]
Shape of 1D tensor is (4,)
After Reshaping 1D tensor to 4 rows 1 column
[[1]
 [2]
 [3]
 [4]]

 Before Reshaping 2D Tensor
[[1 2]
 [3 4]]
Shape of 2D tensor is (2, 2)
After Reshaping 2D tensor to 4 rows 1 column
[[1]
 [2]
 [3]
 [4]]

Before Reshaping 3D Tensor
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of 3D tensor is (2, 2, 2)
After Reshaping 3D tensor to 8rows 1 column
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [1]:
15
import numpy as np
x = np.array([[1,2,3,4],[5,6,7,8]])
print("Before Transposition")
print(x)
print("Shape of x tensor is",x.shape)
x = np.transpose(x)
print("\n After Transposition")
print(x)
print("Shape of x tensor is",x.shape)

Before Transposition
[[1 2 3 4]
 [5 6 7 8]]
Shape of x tensor is (2, 4)

 After Transposition
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Shape of x tensor is (4, 2)
